services:
  ubuntu22.04-dev:
    container_name: ubuntu22.04-dev
    hostname: ubuntu22.04
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - CMAKE_VERSION=3.30.3
        - USERNAME=dev
        - CONAN_VERSION=2.5.0
        - LLVM_VERSION=18
        - MOLD_VERSION=2.33.0
        - VALGRIND_VERSION=3.23
    volumes:
      - ../:/workspace:cached
      # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    cap_add:
      - SYS_PTRACE
    environment:
      # set the ccache folder
      - CCACHE_DIR=/workspace/.ccache
    security_opt:
      - seccomp:unconfined
    tty: true
    working_dir: /workspace
